### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by AlexWayfer** [fishworks/gofi.sh#1]
Hello!

You have non-crossplatform characters in the site about crossplatform tool. :grimacing: 

![image](https://user-images.githubusercontent.com/6510020/38578827-bc2749bc-3d0d-11e8-9f9b-f5e65d5fb6cb.png)

**Comment by bacongobbler** [comment]
Your browser probably is missing a package needed to render emojis. This isn't an issue with the site or the platform, but with your OS. you probably need to install a package like https://github.com/eosrei/twemoji-color-font to get them to render properly. most operating systems have instructions on how to get your browser to properly render emojis.

If you've got a fix that we can apply to the site, I'd happily merge a patch. I don't pretend I'm a front-end designer.

**Comment by AlexWayfer** [comment]
> Your browser probably is missing a package needed to render emojis. This isn't an issue with the site or the platform, but with your OS. you probably need to install a package like https://github.com/eosrei/twemoji-color-font to get them to render properly. most operating systems have instructions on how to get your browser to properly render emojis.

1. I probably need to install a package, other users probably need to install a package, everybody probably need to install non-default package… I think no.
2. I mean, this is strange: you're writing (at site) about cross-platform tool with platform-specific features.
3. The site can don't have these symbols, or the site can use some front-end library for their rendering platform-independent. One time installation, instead of every user on Linux/Windows/etc.

**Comment by bacongobbler** [comment]
Closing this as something I'm not planning on fixing. The site renders fine for me with Firefox on Windows, macOS and Ubuntu with no issues rendering the emojis.

**Comment by AlexWayfer** [comment]
For other users as me:

[Emoji in Arch Linux](https://wiki.archlinux.org/index.php/fonts#Emoji_and_symbols).

`noto-fonts-emoji` works good for me (just browser restart required, nothing else).
